apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-api-feed
  name: udagram-api-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-api-feed
  template:
    metadata:
      labels:
        service: udagram-api-feed
    spec:
      containers:
      - image: njivory10/udagram-api-feed:v2
        name: udagram-api-feed
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"                  
        env:
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: JWT_SECRET
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: URL
        - name: AWS_BUCKET
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_BUCKET
        - name: AWS_PROFILE
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_PROFILE
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_REGION
        - name: AWS_CONFIG_FILE
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_CONFIG_FILE
        - name: AWS_SHARED_CREDENTIALS_FILE
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_SHARED_CREDENTIALS_FILE
        - name: aws_access_key_id
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_access_key_id
        - name: aws_secret_access_key
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_secret_access_key
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_HOST
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_USERNAME      
      restartPolicy: Always

#Attribution credit: https://knowledge.udacity.com/questions/735399